### ISSUE TITLE
What do the additional 17 bytes in FE cluster represent?

### ISSUE THREAD

**Issue by andydvsn** [birdslikewires/hubitat#7]
Search in here for the word "interesting".

https://github.com/jamesleesaunders/PyAlertMe/blob/master/pyalertme/zbnode.py

There are 17 bytes which may contain something in the FE (CLUSTER_CMD_AM_VERSION_RESP) cluster message, but we don't know what they represent. Maybe something, maybe nothing.

Anyone who would like to dig, please do so! :)

**Comment by jrjefferies** [comment]
Andy,

I have looked in the original Alertme hub python code and the decode for that is
```
self.nodeId, nodeEui64str, self.mfgId, self.deviceType, self.appRelease, self.appVersion, self.hwMinorVersion, self.hwMajorVersion = struct.unpack('<H8sHHBBBB', message[:18])
```

So that 17 bytes looks like
2 bytes for short node address
8 bytes for long address
2 bytes for manufacture ID
2 bytes for device type
1 byte for app release
1 byte for app version

Then you already know the next two bytes = HW

I don't know if you thing that is 'interesting' enough to write the decode.

Regards, 
  James

**Comment by andydvsn** [comment]
James! I can't believe it's taken me so long to see this, thank you ever so much for your help.

Hmm, I guess we get all that information elsewhere, so I'll chalk this down as solved and not worry about it. :)

Thank you again, I've been very much off my game with this stuff recently.
